---
name: agrometeo-geopy
channels:
    - conda-forge
dependencies:
    - python=3.9
    - ipykernel=6.9.2
    - mkdocs=1.2.3
    - mkdocs-jupyter=0.20.1
    - pip>=20.1 # pip is needed as dependency
    - pip:
          - mkdocs-include-markdown-plugin==3.3.0
          - mkdocstrings==0.18.0
          - mkdocstrings-python==0.6.6
          - mknotebooks==0.7.1
    - pytkdocs=0.16.1
