name: agrometeo-geopy
channels:
    - conda-forge
dependencies:
    - python=3.10
    - gdal=3.6.3
    - myst-parser=1.0.0
    - nbsphinx=0.9.1
    - sphinx=6.1.3
    - pandoc=2.19.2
    - pip=23.0.1
