name: agrometeo-geopy
channels:
  - conda-forge
dependencies:
  - python=3.9
  - mkdocs=1.2.3
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - mkdocs-include-markdown-plugin==3.3.0
    - mkdocstrings==0.18.0
